@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Laboratory Coordinator" as LC
participant ":System" as S

activate LC

LC -> S: asks to import clinical tests from a CSV file
activate S
S --> LC:   asks to select a .csv file
deactivate S
LC -> S: selects the .csv files
activate S
S --> LC: requests data confirmation
deactivate S
LC -> S: confirms all data
activate S
S --> LC: informs operation success
deactivate S

deactivate LC

@enduml