@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Administrator" as A
participant ":System" as S
activate A


A -> S: asks to create a new test type
activate S
loop
S --> A: shows parameter category list and asks to select one
deactivate S


A -> S: selects a parameter category
activate S
end
S --> A: requests data (description, \n collectingMethod, code)
deactivate S


A -> S: types requested data
activate S
S --> A: shows all data and requests confirmation
deactivate S

A -> S: confirms the data
activate S
S --> A: informs operation success
deactivate S
@enduml