@startuml
RecordSampleUI ..> RecordSampleController
RecordSampleController..>Company
RecordSampleController..>Sample
RecordSampleController..>LabOrderMapper 
RecordSampleController..>SampleDTO
RecordSampleController..>SampleStore
RecordSampleController..>SampleMapper
RecordSampleController..>LabOrderStore




RecordSampleController : +RecordNewSample(dto)
RecordSampleController : +saveNewSample()
RecordSampleController : +getTest()


Company --> SampleStore : have

SampleStore --> Sample: has

Company --> LabOrderStore

LabOrderStore : +getTestByTestTypeCode(testid)

LabOrderMapper ..> LabOrderDTO
LabOrderDTO..> LabOrder
Sample --> LabOrder: originated from


LabOrderStore --> LabOrder : Has
SampleMapper ..> SampleDTO


LabOrderMapper ..> LabOrderStore


LabOrder : -testType


LabOrderMapper : +toDTO(tests)

SampleMapper : +toModel()




Company : +getTestStore()
Company : +getSampleStore()

SampleStore : +RecordNewSample(tdo)
SampleStore : +validateNewSample(samp)
SampleStore : +saveNewSample(samp)
SampleStore : +addNewSample(samp)

SampleDTO : +getTimeColl()
SampleDTO : +getDataColl()
SampleDTO : +getgetTestId()


SampleDTO : -timeCollection
SampleDTO : -dateCollection


Sample : +Sample(dataCollection, timeCollection, test)
Sample : -timeCollection
Sample : -dateCollection
@enduml