@startuml
actor "Medical Lab Technician" as Adm
participant ":RecordSampleUI" as Interface
participant ":RecordSampleController" as Controller
participant ":Company" as Company
participant ":TestMapper" as TM
participant "tStore \n :TestStore" as SS
participant "SampleMapper" as SM
participant "SampDto: SampleDto" as SD
participant "store \n :LabOrderStore" as TS


 
 
autonumber
activate Adm
Adm -> Interface: starts recording a new sample
activate Interface
Interface -> Controller: testDto = getTest()
activate Controller
Controller -> Company : tStore=getTestStore()
activate Company
deactivate Company
Controller -> SS: test = getTest()
activate SS
deactivate SS
Controller -> TM: testDto = toDTO(test)
activate TM

TM-->Controller : testDto
deactivate TM
Controller-->Interface : testDto
deactivate Controller
Interface --> Adm: shows the list of tests registered to be performed and requests to select one of them
deactivate Interface



Adm -> Interface: select a test registered to be performed
activate Interface
Interface--> Adm: request how many samples want to record
deactivate Interface

Adm -> Interface : type the requested data


activate Interface

Interface->Controller: RecordNewSample(dto)
activate Controller
Controller -> Company : sampleStore=getSampleStore()
activate Company
Deactivate Company
Controller->SS: samp=RecordNewSample(dto)
activate SS


SS->SM: toModel(dto)
activate SM
SM->SD: orderid=getOrderId()
activate SD
deactivate SD
SM->TS: testype=getTestTypeByOrderId(order)
activate TS
deactivate TS




create "samp: Sample" as samp
SM->samp:  create(testype)



deactivate SM
deactivate SS

Controller->SS:validateNewSample(samp)
Activate SS
deactivate SS

deactivate Controller


Interface-->Adm : shows the data and requests a confirmation

deactivate Interface

Adm -> Interface: confirms the data
activate Interface
Interface->Controller: saveNewSample()
activate Controller
Controller->SS:saveNewSample(samp)
activate SS
SS->SS:validateNewSample(samp)
activate SS
deactivate SS
SS->SS:addSample(samp)
activate SS
deactivate SS

deactivate SS
deactivate Controller
Interface--> Adm: informs operation success

deactivate Interface
deactivate Adm
@enduml