@startuml
actor Administrator as Adm
participant ":RecordSampleUI" as Interface
participant ":RecordSampleController" as Controller
participant ":Company" as Company
participant ":TestMapper" as TM
participant "store \n :SampleStore" as SS
participant "SampleMapper" as SM
participant "SampDto: SampleDto" as SD
participant "store \n :TestStore" as TS




 
 
autonumber
activate Adm
Adm -> Interface: starts recording a new sample
activate Interface
Interface -> Controller: testsDto = getTest()
activate Controller
Controller -> TS: tests = getTest()
activate TS
deactivate TS
Controller -> TM: testsDto = toDTO(tests)
activate TM
deactivate TM
deactivate Controller
Interface --> Adm: ask to select the test to record the sample
deactivate Interface



Adm -> Interface: selects the intended test
activate Interface
Interface --> Adm: request data (descriptionMethod, dateCollection, timeCollection)
deactivate Interface


Adm -> Interface: types requested data
activate Interface
Interface-->Controller: createNewClient(dto)
activate Controller
Controller-->SS: nc=createNewClient(dto)
activate SS


SS-->SM: toModel(dto)
activate SM
SM-->SD: description=getDescription()
activate SD
deactivate SD
SM-->SD: dataColl=getDataColl()
activate SD
deactivate SD
SM-->SD: timeColl=getTimeColl()
activate SD
deactivate SD
SM-->TS: test=getTestByCode()
activate TS
deactivate TS




create "samp: Sample" as samp
SM-->samp:  create(description,dataColl,timeColl,test)



deactivate SM
deactivate SS

Controller-->SS:validateNewClient(nc)
Activate SS
deactivate SS

deactivate Controller

Interface--> Adm: shows the data and request a confirmation
deactivate Interface


Adm -> Interface: confirms the data
activate Interface
Interface-->Controller: saveNewClient()
activate Controller
Controller-->SS:saveNewClient(nc)
activate SS
SS-->SS:validateNewClient(nc)
activate SS
deactivate SS
SS-->SS:addNewClient(nc)
activate SS
deactivate SS
SS-->SS:sendEmail(nc)
activate SS
deactivate SS

deactivate SS
deactivate Controller
Interface--> Adm: informs operation success

deactivate Interface
deactivate Adm
@enduml