@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Client" as C
participant ":System" as S
activate C

C -> S: asks to show the results of the tests performed by the client

activate S
S --> C: shows the order list of tests and asks to select one
deactivate S

C -> S: selects one of them

activate S
S --> C: shows the results associated with the selected test
deactivate S

C -> S: confirms the data
activate S
S --> C: informs operation success
deactivate S
deactivate C

@enduml