@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0


class Company {
  -designation
}

class Test {
  -report
}

class ParameterResult {
  -parameter
  -testParameterResult
}

class Report {
  -diagnosis
  -createdAt
}

Company "1" -- "*" Test : performs  >
Test "1" -- "*" TestParameter : request analysis of >
Report "1" -- "1" Test : created according to >
ParameterResult "1..*" -- "1" Test : obtained through >

@enduml