@startuml
actor Receptionist as Adm
participant ":RegistClient UI" as System
participant ":RegistClientCrontroller" as RCC
participant ":Company" as ML
participant ":ClientMapper" as cm
participant "dto:ClientDTO" as cdto


autonumber
activate Adm
Adm -> System: starts new Client
activate System
System --> Adm: request data(CCN, National Healthcare Service (NHS) number,\n Birth date, Sex(Opcional), Tax Identification number (TIF), E-mail, Name, Phone number)
deactivate System




Adm -> System: types requested data
activate System
System-->RCC: createNewClient(dto)
activate RCC
RCC-->ML: nc=createNewClient(dto)
activate ML


ML-->cm: toModel(dto)
activate cm
cm-->cdto: ccn=getCCN()
activate cdto
deactivate cdto
cm-->cdto: nhs=getNHS()
activate cdto
deactivate cdto
cm-->cdto: birthDate=getBirthDate()
activate cdto
deactivate cdto
cm-->cdto: sex=getSex()
activate cdto
deactivate cdto
cm-->cdto: tif=getTIF()
activate cdto
deactivate cdto
cm-->cdto: email=getEmail()
activate cdto
deactivate cdto
cm-->cdto: name=getName()
activate cdto
deactivate cdto
cm-->cdto: phoneNumber=getPhoneNumber()
activate cdto
deactivate cdto


create "nc: Client" as NC
cm-->NC:  create(ccn, nhs, birthDate, sex, tif,\n email, name, phoneNumber)



deactivate cm
deactivate ML

RCC-->ML:validateNewClient(NC)
Activate ML
deactivate ML

deactivate RCC

System --> Adm: shows the data and request a confirmation
deactivate System


Adm -> System: confirms the data
activate System
System-->RCC: saveNewClient()
activate RCC
RCC-->ML:saveNewClient(NC)
activate ML
ML-->ML:validateNewClient(NC)
activate ML
deactivate ML
ML-->ML:addNewClient(NC)
activate ML
deactivate ML
ML-->NC:sendEmail(NC)
activate NC
deactivate NC
deactivate ML
deactivate RCC
System --> Adm: informs operation success
deactivate System
deactivate Adm
@enduml