@startuml
actor "Laboratory Coordinator" as Adm
participant ":System" as System

autonumber
activate Adm
Adm -> System: ask to validate the work done by the clinical \nchemistry technologist and specialist doctor
activate System
System --> Adm: shows the tests ready to be validated
deactivate System
Adm -> System: select the test to validate
activate System
System --> Adm: shows the dates
deactivate System
Adm -> System: validate
activate System
System --> Adm: request confirmation
deactivate System
Adm -> System: confirms
activate System
System --> Adm: informs operations success
deactivate System
deactivate Adm
@enduml