@startuml
'https://plantuml.com/sequence-diagram

autonumber


actor "Client" as C
participant ":System" as S
activate C



C -> S: asks to update its personal data
activate S
S --> C: shows client's personal data and asks him to select a field
deactivate S
loop
C -> S: selects a field
activate S
S --> C: requests data
deactivate S
C -> S: types requested data
activate S
S --> C: shows all data and requests confirmation
deactivate S
C -> S: confirms the data
activate S
S --> C: shows operation success
deactivate S
end

deactivate C



@enduml